App config available from @gasket/data
godaddy/gasket pull request #231
Opened 2020-12-17 18:58 UTC by kawikabader

## Summary

We need a way for app config to be made available in the browser, when Redux is not used. Today, teams can set config under a Redux property which will make it available in the Redux store.

For this change, we introduced a new special property (public) which will add its values to res.locals.gasketData.config, and thus be made available in the browser under with @gasket/data as gasketData.config.

## Test Plan

Tests updated.

2020-12-17 19:59 UTC, kinetifex requested changes

2020-12-17 19:59 UTC, kinetifex commented on packages/gasket-plugin-config/README.md
> +The config plugin will return these `public` properties to your browser, to be accessed by the `@gasket/data` plugin, and used like so:
Refer to `@gasket/data` as a package or module, to distinguish it from a Gasket plugin (with lifecycle hooks, etc)
```suggestion
The config plugin will return these `public` properties to your browser, to be accessed by `@gasket/data`, and used like so:
```

2020-12-17 19:59 UTC, kinetifex commented on packages/gasket-plugin-config/README.md
> +The config plugin will return these `public` properties to your browser, to be accessed by the `@gasket/data` plugin, and used like so:
Also, describe that what's placed in `public` in the config files, is accessible as `.config` from gasketData. You show that in the example, but should describe it.

2020-12-17 21:13 UTC, kinetifex approved these changes

2020-12-18 07:37 UTC, mswaagman-godaddy approved these changes

2020-12-18 14:50 UTC, merged