Create attach gitignore hook.
godaddy/gasket pull request #344
Opened 2022-03-04 18:52 UTC by kawikabader

## Summary

## Changelog

## Test Plan

2022-03-07 23:20 UTC, jpage-godaddy approved these changes
Nice extensible approach.

2022-03-08 15:53 UTC, kinetifex requested changes
The code looks good but we need some docs.

2022-03-08 20:59 UTC, kawikabader commented
@kinetifex Just added docs. 👍🏻

2022-03-08 21:46 UTC, kinetifex approved these changes

2022-03-08 21:57 UTC, merged