Remove duplicate next link in README
godaddy/gasket pull request #408
Opened 2022-08-11 12:18 UTC by Zeedinstein

Noticed a duplicate link in the readme that was unnecessary.

2022-08-11 15:06 UTC, jpage-godaddy approved these changes

2022-08-11 15:06 UTC, jpage-godaddy commented
Is this auto-generated code, though? I wonder how it got generated as a duplicate.

2022-08-11 15:09 UTC, jpage-godaddy requested changes
Actually, this is for sure generated code. Looks like the reason it was duplicated is here:

https://github.com/godaddy/gasket/blob/main/packages/gasket-plugin-nextjs/lib/index.js#L242-L265

2022-08-12 08:14 UTC, Zeedinstein commented
Sure I'll have a look at that

2022-08-12 08:26 UTC, Zeedinstein commented
@jpage-godaddy This should now only generate the one next link. Which I don't see a problem with. Unless having 2 links was done on purpose for express and fastify? But I still don't see a reason to have 2 next links.

2022-08-15 16:08 UTC, jpage-godaddy commented
> @jpage-godaddy This should now only generate the one next link. Which I don't see a problem with. Unless having 2 links was done on purpose for express and fastify? But I still don't see a reason to have 2 next links.

Hm, yeah I didn't notice until now that they had different parents, so they're not really duplicated. When the lifecycle diagram is generated, those two `next` entries are both used. It sounds like the script that generates the markdown documentation is the real issue; that needs to do the de-duplication. Finding where that bug in the documentation generation code is would be key here.

2022-08-16 17:39 UTC, agerard-godaddy commented on packages/gasket-plugin-nextjs/lib/index.js
> -          name: 'next',
Good catches and thanks for being willing to contribute @Zeedinstein. As @jpage-godaddy mentioned, we would still need this entry for the graph generation.

So yea, a couple issues... we should probably only generated one or the other depending on which, either Express or Fastify, Gasket plugins are in use by an app when using the `gasket docs` command. However, that still will not address the duplication in the generated index readme for the repo here. I think the duplication will be necessary, with the best thing to do being to clarify things in the descriptions:
- `Update the Next.js app instance before preparing for Express`
- `Update the Next.js app instance before preparing for Fastify`

2022-10-10 22:50 UTC, agerard-godaddy commented
Resolved in https://github.com/godaddy/gasket/pull/472

2022-10-10 22:50 UTC, closed without merging