feat: add sitemap prompt to nextjs-plugin
godaddy/gasket pull request #479
Opened 2022-10-31 16:11 UTC by jpina1-godaddy

## Summary

Adds the ability to add a sitemap to Gasket applications using nextjs

## Changelog

@gasket/plugin-nextjs

- Added confirmation prompt for adding a sitemap

## Test Plan

- Updated unit tests

2022-11-02 15:08 UTC, agerard-godaddy requested changes
Add a brief section to the Readme about `next-sitemap` being optionally installed, with a link to their docs so that users can understand what the prompt is asking and where to learn more.

2022-11-02 15:08 UTC, agerard-godaddy commented on packages/gasket-plugin-nextjs/lib/index.js
> +      const { addSitemap } = await prompt([
Add a safety check incase `addSitemap` was already added to the create context as we similarly bumped into with https://github.com/godaddy/gasket/pull/480
```suggestion
      if(!('addSitemap' in context)) {
        const { addSitemap } = await prompt([
```
Include a test for this condition as well.

2022-11-02 16:46 UTC, agerard-godaddy approved these changes
Fix a few typos then 👍

2022-11-02 16:46 UTC, agerard-godaddy commented on packages/gasket-plugin-nextjs/README.md
> +Answering yes to this question will install `next-sitemap` as a dependency, generate a next-sitemap.config.js file, and add a `sitemap` npm script to your package.json. `next-sitemap` is an npm packa
```suggestion
When creating a new application with this plugin, you will be prompted with a question in the CLI asking if you would like to add a [sitemap] to your application. 

Answering yes to this question will install `next-sitemap` as a dependency, generate a next-sitemap.config.js file, and add a `sitemap` npm script to your package.json. `next-sitemap` is an npm package that generates sitemaps and a robots.txt file for Next.js applications. Learn more by reading the [next-sitemap docs].
```

2022-11-03 17:04 UTC, mmason2-godaddy approved these changes

2022-11-03 20:44 UTC, merged