Add multi-dependency support for requireWithInstall in @gasket/utils
godaddy/gasket pull request #500
Opened 2023-01-04 23:21 UTC by jpina1-godaddy

## Summary

Update `requireWithInstall` to support multiple dependencies.

## Changelog

@gasket/utils

- Add the option for an array of dependencies to the first parameter in `requireWithInstall`.

## Test Plan

- Added unit tests and tested functionality with a local gasket app.

2023-01-05 18:44 UTC, mmason2-godaddy approved these changes
👍

2023-01-11 17:54 UTC, agerard-godaddy requested changes

2023-01-11 17:54 UTC, agerard-godaddy commented on packages/gasket-utils/lib/require-with-install.js
> +  }
What we need with the multi-dependency support is for the underlying `npm` call to be executed once with the list of modules to install. i.e. we should see
```
npm install my-package @scoped/package --no-save
```
and not
```
npm install my-package --no-save
npm install @scoped/package --no-save
```

The problem being, when the second install happens, npm will remove the previously installed but not saved package from node_modules.

2023-01-18 17:58 UTC, agerard-godaddy commented on packages/gasket-utils/test/require-with-install.test.js
> +    it('allows for the first parameter to be an array of strings', async function () {
Could you include in this test (or a separate one) a check that the packageManager (using `packageManagerExecStub`) is called with both packages for the install command?

2023-01-18 18:38 UTC, agerard-godaddy approved these changes

2023-01-18 18:50 UTC, merged