[PFX-454] - fix broken jest tests in @godaddy/webapp apps
godaddy/gasket pull request #678
Opened 2024-02-16 00:19 UTC by mmason2-godaddy

## Summary
**First Error**
**Error:** Jest could not parse the `css` imports and the `@ux/pivot/style` import correctly.
**Fix**:
![Screenshot 2024-02-15 at 4 15 48 PM](https://github.com/godaddy/gasket/assets/105235096/86c38840-59d1-4929-94e9-1a56ff2c340f)

**Second Error**
**Error:** `[React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.` For whatever reason `react-intl` wasn't working properly.
**Fix:**
![Screenshot 2024-02-15 at 4 17 33 PM](https://github.com/godaddy/gasket/assets/105235096/85278c7d-cf55-4d97-b928-939151e3e56b)

**Third Error(Original error)**
**Error:** `Error: Not implemented: window.computedStyle(elt, pseudoElt)`
**Fix:**
![Screenshot 2024-02-15 at 4 18 38 PM](https://github.com/godaddy/gasket/assets/105235096/fc915248-5711-4e7f-9d31-c1d123a04e49)

## Changelog

## Test Plan

2024-02-16 15:19 UTC, agerard-godaddy requested changes

2024-02-16 15:19 UTC, agerard-godaddy commented on packages/gasket-plugin-jest/generator/jest.config.js
> +    '@ux/pivot/styles': '<rootDir>/test/style-mock.js'
Adding a style mock for css import is a good call.

However, the next mapper appears to be an app-specific import. This generated example jest config should not have it. If anything, add a comment or link to docs about customizing further.
```suggestion
```

2024-02-19 17:01 UTC, mmason2-godaddy commented
So here's the PR that added the pivot styles -> https://github.com/gdcorp-uxp/gasket/pull/1338/files

Are we thinking I should just remove that and leave it broken?

2024-02-20 16:07 UTC, agerard-godaddy commented on packages/gasket-plugin-nextjs/generator/jest/test/index.spec.js
> +jest.mock('react-intl');
I understand this is a preemptive example mock - but does it blow up if `react-intl` is NOT installed for a particular app? If it still works, then I think it's fine to leave here, but add a comment about why it is in the example test for users to follow up on.

2024-02-20 17:31 UTC, agerard-godaddy commented on packages/gasket-plugin-nextjs/generator/jest/test/index.spec.js
> +jest.mock('react-intl');
I was able to test it out and confirm it works.

2024-02-20 17:36 UTC, agerard-godaddy approved these changes

2024-02-20 17:48 UTC, kbader-godaddy approved these changes

2024-02-20 18:05 UTC, merged