feat: added gasket data layout
godaddy/gasket pull request #814
Opened 2024-07-23 17:09 UTC by jpina1-godaddy

## Summary

## Changelog

## Test Plan

2024-07-23 23:01 UTC, agerard-godaddy requested changes

2024-07-23 23:01 UTC, agerard-godaddy commented on packages/gasket-nextjs/test/layout/with-gasket-data-layout.test.js
> +    function createMockJsx() {
also not jsx here

2024-07-24 20:08 UTC, agerard-godaddy commented on packages/gasket-nextjs/package.json
> +  "gitHead": "d96c86a52f608ea702f9b91a5a72f3b19389877c"
```suggestion
  }
```

2024-07-24 20:10 UTC, agerard-godaddy commented on packages/gasket-nextjs/test/inject-gasket-data.test.js
> +     */
Either give it a jsdoc or disable since it's a test helper
```suggestion
// eslint-disable-next-line jsdoc/require-jsdoc
```

2024-07-24 20:10 UTC, agerard-godaddy commented on packages/gasket-nextjs/test/layout/with-gasket-data.test.js
> +     */
Either give it a jsdoc or disable since it's a test helper
```suggestion
// eslint-disable-next-line jsdoc/require-jsdoc
```

2024-07-24 20:10 UTC, agerard-godaddy approved these changes
Couple small things then 👍

2024-07-29 22:09 UTC, mmason2-godaddy approved these changes

2024-07-29 23:35 UTC, merged