Pfx 555
godaddy/gasket pull request #817
Opened 2024-07-27 00:27 UTC by jpina1-godaddy

## Summary

## Changelog

## Test Plan

2024-07-29 22:09 UTC, mmason2-godaddy approved these changes

2024-07-29 22:56 UTC, agerard-godaddy requested changes

2024-07-29 22:56 UTC, agerard-godaddy commented on packages/create-gasket-app/README.md
> +const hooks= {
```suggestion
const hooks = {
```

2024-07-29 22:56 UTC, agerard-godaddy commented on packages/gasket-plugin-log/README.md
> +# @gasket/plugin-log
Whoa whoa - this plugin should be gone and replaced with `@gasket/plugin-logger`

2024-07-29 22:56 UTC, agerard-godaddy commented on packages/gasket-plugin-winston/README.md
> -
Let's keep an example of the hook here

```js
// sample-plugin.js
const fluent = require('fluent-logger');
const FluentTransport = fluent.support.winstonTransport();

export default {
  name: 'sample-plugin',
  hooks: {
    winstonTransports(gasket) {
      return new FluentTransport('mytag', gasket.config.fluentd);
    }
  }
};
```

2024-07-30 15:41 UTC, agerard-godaddy commented on packages/create-gasket-app/README.md
> +  async prompt(gasket, context, { prompt, addPlugins }) {
`addPlugins` and the example usage below are no longer valid

2024-07-30 15:41 UTC, agerard-godaddy commented on packages/gasket-plugin-lint/README.md
> +// presetPrompt.js
nit: keep consistent file name pattern
```suggestion
// preset-prompt.js
```

2024-07-30 15:41 UTC, agerard-godaddy commented on packages/gasket-plugin-lint/README.md
> +// presetPrompt.js
nit: keep consistent file name pattern
```suggestion
// preset-prompt.js
```

2024-07-30 17:50 UTC, agerard-godaddy approved these changes
Nice work!

2024-07-30 18:38 UTC, merged