[PFX-714]: Gasket logger is showing incorrect formatting
godaddy/gasket pull request #870
Opened 2024-08-26 21:06 UTC by bbetts-godaddy

## Summary

[Ticket](https://godaddy-corp.atlassian.net/browse/PFX-714)

Log messages using the winston logger were being displayed in a json object. The goal is to display just the message in the console. 

## Changelog

- update default winston format to be `format.simple()`

## Test Plan

<img width="532" alt="Screenshot 2024-08-26 at 2 06 47 PM" src="https://github.com/user-attachments/assets/bb04b2f0-5993-4fc9-939a-6f85b4bc2653">
- all tests are passing in the winston plugin

2024-08-26 23:31 UTC, mmason2-godaddy approved these changes

2024-08-27 00:21 UTC, jpina1-godaddy approved these changes

2024-08-27 18:31 UTC, agerard-godaddy requested changes

2024-08-27 18:31 UTC, agerard-godaddy commented on packages/gasket-plugin-winston/lib/index.js
> +          format.simple(),
We would still want to default to `format.combine(format.splat(), format.json())` and only use `format.simple()` when the env is local.

```js
const defaultFormat = gasket.config.env.startsWith('local') ? format.simple() : format.combine(format.splat();
```

```sugggestion
format: config.winston?.format ?? defaultFormat
```

2024-08-27 22:38 UTC, agerard-godaddy approved these changes

2024-08-28 17:33 UTC, merged